# Generated by Django 3.1 on 2020-09-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todo_prioirty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='prioirty',
            new_name='prioirity',
        ),
    ]
