# Generated by Django 3.1 on 2020-08-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='todo-item')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료여부')),
            ],
        ),
    ]
