# Generated by Django 3.1 on 2020-09-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200902_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='prioirty',
            field=models.IntegerField(choices=[(1, 'TOP'), (2, 'MIDDLE'), (3, 'BOTTOM')], default=1),
            preserve_default=False,
        ),
    ]
