# Generated by Django 3.1 on 2020-09-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200902_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='prioirity',
            new_name='priority',
        ),
    ]
